### ISSUE TITLE
enableStencil function

### ISSUE THREAD

**Issue by Wyvest** [Deftu/OmniCore#1]
Needed in `MultiGlStateManager`

**Comment by Deftu** [comment]
Might need help finding out how to implement this for modern versions. I'm unsure of if stencil is enabled by default or not. It might be?

**Comment by Wyvest** [comment]
It isn’t. Requires a mixin.Sent from my iPadOn Apr 7, 2023, at 6:39 AM, Deftu ***@***.***> wrote:﻿
Might need help finding out how to implement this for modern versions. I'm unsure of if stencil is enabled by default or not. It might be?

**Comment by Deftu** [comment]
I would prefer if I wouldn't need to use a Mixin within this library.
